export const IMAGE_LEFT = 'right'
export const IMAGE_RIGHT = 'right'
export const SHOWCASE = 'showcase'
export const EMAIL_FORMAT_REGEX = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/i;
export const NAME_IS_EMPTY = 'nameIsEmpty'
export const EMAIL_IS_EMPTY = 'emailIsEmpty'
export const EMAIL_IS_NOT_FORMATTED = 'emailIsNotFormatted'
export const MESSAGE_IS_EMPTY = 'messageIsEmpty';
export const FORM_SUBMIT_URL = 'https://formsubmit.io/send/hello@thesquaredev.com'
export const CONTACT_FORM_RESPONSE_SUCCESS = 'We got your message. Thank you.'
export const CONTACT_FORM_RESPONSE_FAILURE = 'Something went wrong. Please try again.'
export const BACKGROUND_SIZE_CONTAIN = 'contain'
export const BACKGROUND_SIZE_COVER = 'cover'
